# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Valen\Documents\PROJECTS\.pipeline\all\ui\cioxo_createFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence,
                           QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import ui_cioxo_QtResources_rc


class Ui_cioxo_createFile(object):
    def setupUi(self, cioxo_createFile):
        cioxo_createFile.setObjectName("cioxo_createFile")
        cioxo_createFile.resize(473, 339)
        cioxo_createFile.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(cioxo_createFile)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_all = QtWidgets.QFrame(cioxo_createFile)
        self.frame_all.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_all.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_all.setLineWidth(0)
        self.frame_all.setObjectName("frame_all")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_all)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_title = QtWidgets.QFrame(self.frame_all)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_title.setStyleSheet("")
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_title.setLineWidth(0)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_6.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_createFile = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_createFile.setFont(font)
        self.label_createFile.setStyleSheet("color:white;")
        self.label_createFile.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_createFile.setObjectName("label_createFile")
        self.horizontalLayout_6.addWidget(self.label_createFile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_title)
        self.frame_input = QtWidgets.QFrame(self.frame_all)
        self.frame_input.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_input.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_input.setLineWidth(0)
        self.frame_input.setObjectName("frame_input")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_input)
        self.verticalLayout_2.setContentsMargins(9, -1, 9, 6)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_actualFile = QtWidgets.QFrame(self.frame_input)
        self.frame_actualFile.setStyleSheet("")
        self.frame_actualFile.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_actualFile.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_actualFile.setObjectName("frame_actualFile")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_actualFile)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2.addWidget(self.frame_actualFile)
        self.frame_fileInput = QtWidgets.QFrame(self.frame_input)
        self.frame_fileInput.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame_fileInput.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_fileInput.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_fileInput.setLineWidth(0)
        self.frame_fileInput.setObjectName("frame_fileInput")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_fileInput)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_actualProject = QtWidgets.QLabel(self.frame_fileInput)
        self.label_actualProject.setMinimumSize(QtCore.QSize(30, 21))
        self.label_actualProject.setMaximumSize(QtCore.QSize(30, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_actualProject.setFont(font)
        self.label_actualProject.setStyleSheet("    background-color: rgb(50, 50, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"    border-color: rgb(50, 50, 50);")
        self.label_actualProject.setObjectName("label_actualProject")
        self.horizontalLayout.addWidget(self.label_actualProject)
        self.label_actualSequence = QtWidgets.QLabel(self.frame_fileInput)
        self.label_actualSequence.setMinimumSize(QtCore.QSize(65, 21))
        self.label_actualSequence.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_actualSequence.setFont(font)
        self.label_actualSequence.setStyleSheet("    background-color: rgb(50, 50, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"    border-color: rgb(50, 50, 50);")
        self.label_actualSequence.setObjectName("label_actualSequence")
        self.horizontalLayout.addWidget(self.label_actualSequence)
        self.label_actualShot = QtWidgets.QLabel(self.frame_fileInput)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_actualShot.setFont(font)
        self.label_actualShot.setStyleSheet("    background-color: rgb(50, 50, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"    border-color: rgb(50, 50, 50);")
        self.label_actualShot.setObjectName("label_actualShot")
        self.horizontalLayout.addWidget(self.label_actualShot)
        self.comboBox_discipline = QtWidgets.QComboBox(self.frame_fileInput)
        self.comboBox_discipline.setMinimumSize(QtCore.QSize(100, 21))
        self.comboBox_discipline.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_discipline.setFont(font)
        self.comboBox_discipline.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(50, 50, 50);\n"
"}\n"
"QComboBox:item {\n"
"   color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.comboBox_discipline.setEditable(True)
        self.comboBox_discipline.setObjectName("comboBox_discipline")
        self.comboBox_discipline.addItem("")
        self.comboBox_discipline.addItem("")
        self.comboBox_discipline.addItem("")
        self.comboBox_discipline.addItem("")
        self.comboBox_discipline.addItem("")
        self.comboBox_discipline.addItem("")
        self.comboBox_discipline.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_discipline)
        self.lineEdit_version = QtWidgets.QLineEdit(self.frame_fileInput)
        self.lineEdit_version.setMinimumSize(QtCore.QSize(63, 21))
        self.lineEdit_version.setMaximumSize(QtCore.QSize(63, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lineEdit_version.setFont(font)
        self.lineEdit_version.setStyleSheet("\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(50, 50, 50);\n"
"")
        self.lineEdit_version.setObjectName("lineEdit_version")
        self.horizontalLayout.addWidget(self.lineEdit_version)
        self.verticalLayout_2.addWidget(self.frame_fileInput)
        self.frame_comment = QtWidgets.QFrame(self.frame_input)
        self.frame_comment.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_comment.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_comment.setLineWidth(0)
        self.frame_comment.setObjectName("frame_comment")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_comment)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plainTextEdit_comment = QtWidgets.QPlainTextEdit(self.frame_comment)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.plainTextEdit_comment.setFont(font)
        self.plainTextEdit_comment.setStyleSheet("    background-color: rgb(50, 50, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"    border-color: rgb(50, 50, 50);")
        self.plainTextEdit_comment.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit_comment.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_comment.setObjectName("plainTextEdit_comment")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_comment)
        self.verticalLayout_2.addWidget(self.frame_comment)
        self.verticalLayout.addWidget(self.frame_input)
        self.frame_informations = QtWidgets.QFrame(self.frame_all)
        self.frame_informations.setStyleSheet("")
        self.frame_informations.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_informations.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_informations.setLineWidth(0)
        self.frame_informations.setObjectName("frame_informations")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_informations)
        self.verticalLayout_4.setContentsMargins(9, 0, 9, 18)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_informations = QtWidgets.QLabel(self.frame_informations)
        self.label_informations.setMinimumSize(QtCore.QSize(0, 50))
        self.label_informations.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label_informations.setFont(font)
        self.label_informations.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_informations.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(50, 50, 50);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 255, 255);\n"
"    selection-background-color: lightgray;\n"
"}")
        self.label_informations.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_informations.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_informations.setWordWrap(True)
        self.label_informations.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_informations.setObjectName("label_informations")
        self.verticalLayout_4.addWidget(self.label_informations)
        self.verticalLayout.addWidget(self.frame_informations)
        self.frame_choice = QtWidgets.QFrame(self.frame_all)
        self.frame_choice.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_choice.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_choice.setStyleSheet("    background-color: rgb(50, 50, 50);")
        self.frame_choice.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_choice.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_choice.setLineWidth(0)
        self.frame_choice.setObjectName("frame_choice")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_choice)
        self.horizontalLayout_9.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(10, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_separator = QtWidgets.QLabel(self.frame_choice)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_separator.setFont(font)
        self.label_separator.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_separator.setText("")
        self.label_separator.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_separator.setObjectName("label_separator")
        self.horizontalLayout_9.addWidget(self.label_separator)
        self.button_ok = QtWidgets.QPushButton(self.frame_choice)
        self.button_ok.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button_ok.setFont(font)
        self.button_ok.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        self.button_ok.setObjectName("button_ok")
        self.horizontalLayout_9.addWidget(self.button_ok)
        spacerItem2 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.button_cancel = QtWidgets.QPushButton(self.frame_choice)
        self.button_cancel.setMinimumSize(QtCore.QSize(0, 20))
        self.button_cancel.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button_cancel.setFont(font)
        self.button_cancel.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout_9.addWidget(self.button_cancel)
        self.verticalLayout.addWidget(self.frame_choice)
        self.verticalLayout_3.addWidget(self.frame_all)

        self.retranslateUi(cioxo_createFile)
        QtCore.QMetaObject.connectSlotsByName(cioxo_createFile)

    def retranslateUi(self, cioxo_createFile):
        _translate = QtCore.QCoreApplication.translate
        cioxo_createFile.setWindowTitle(_translate("cioxo_createFile", "Dialog"))
        self.label_createFile.setText(_translate("cioxo_createFile", "Create File"))
        self.label_actualProject.setText(_translate("cioxo_createFile", "  pro"))
        self.label_actualSequence.setText(_translate("cioxo_createFile", "  seq001"))
        self.label_actualShot.setText(_translate("cioxo_createFile", "  sh0000"))
        self.comboBox_discipline.setItemText(0, _translate("cioxo_createFile", "none"))
        self.comboBox_discipline.setItemText(1, _translate("cioxo_createFile", "research"))
        self.comboBox_discipline.setItemText(2, _translate("cioxo_createFile", "modeling"))
        self.comboBox_discipline.setItemText(3, _translate("cioxo_createFile", "rigging"))
        self.comboBox_discipline.setItemText(4, _translate("cioxo_createFile", "lookdev"))
        self.comboBox_discipline.setItemText(5, _translate("cioxo_createFile", "lighting"))
        self.comboBox_discipline.setItemText(6, _translate("cioxo_createFile", "rendering"))
        self.lineEdit_version.setText(_translate("cioxo_createFile", "001"))
        self.label_informations.setText(_translate("cioxo_createFile", ">>> Terminal - Choose a discipline and version for the new file"))
        self.button_ok.setText(_translate("cioxo_createFile", "OK"))
        self.button_cancel.setText(_translate("cioxo_createFile", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cioxo_createFile = QtWidgets.QDialog()
    ui = Ui_cioxo_createFile()
    ui.setupUi(cioxo_createFile)
    cioxo_createFile.show()
    sys.exit(app.exec_())
