# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Valen\Documents\PROJECTS\.pipeline\all\ui\createProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence,
                           QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import ui_cioxoQtResources_rc


class Ui_CreateProject(object):
    def setupUi(self, CreateProject):
        CreateProject.setObjectName("CreateProject")
        CreateProject.resize(500, 250)
        CreateProject.setMinimumSize(QtCore.QSize(500, 250))
        CreateProject.setMaximumSize(QtCore.QSize(500, 250))
        CreateProject.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(CreateProject)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameAll = QtWidgets.QFrame(CreateProject)
        self.frameAll.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAll.setObjectName("frameAll")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameAll)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameTitle = QtWidgets.QFrame(self.frameAll)
        self.frameTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frameTitle.setStyleSheet("")
        self.frameTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitle.setLineWidth(0)
        self.frameTitle.setObjectName("frameTitle")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frameTitle)
        self.horizontalLayout_6.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelCreateProject = QtWidgets.QLabel(self.frameTitle)
        self.labelCreateProject.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCreateProject.setFont(font)
        self.labelCreateProject.setStyleSheet("color:white;")
        self.labelCreateProject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCreateProject.setObjectName("labelCreateProject")
        self.horizontalLayout_6.addWidget(self.labelCreateProject)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frameTitle)
        self.frameInput = QtWidgets.QFrame(self.frameAll)
        self.frameInput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInput.setObjectName("frameInput")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameInput)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditInput = QtWidgets.QLineEdit(self.frameInput)
        self.lineEditInput.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lineEditInput.setFont(font)
        self.lineEditInput.setStyleSheet("QLineEdit\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(50, 50, 50);\n"
"}")
        self.lineEditInput.setObjectName("lineEditInput")
        self.verticalLayout_2.addWidget(self.lineEditInput)
        self.frameResolution = QtWidgets.QFrame(self.frameInput)
        self.frameResolution.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameResolution.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameResolution.setObjectName("frameResolution")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameResolution)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelResolutionX = QtWidgets.QLabel(self.frameResolution)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.labelResolutionX.setFont(font)
        self.labelResolutionX.setStyleSheet("color:  rgb(200, 200, 200);")
        self.labelResolutionX.setObjectName("labelResolutionX")
        self.horizontalLayout.addWidget(self.labelResolutionX)
        self.lineEditResolutionX = QtWidgets.QLineEdit(self.frameResolution)
        self.lineEditResolutionX.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lineEditResolutionX.setFont(font)
        self.lineEditResolutionX.setStyleSheet("QLineEdit\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(50, 50, 50);\n"
"}")
        self.lineEditResolutionX.setObjectName("lineEditResolutionX")
        self.horizontalLayout.addWidget(self.lineEditResolutionX)
        self.labelResolutionY = QtWidgets.QLabel(self.frameResolution)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.labelResolutionY.setFont(font)
        self.labelResolutionY.setStyleSheet("color:  rgb(200, 200, 200);")
        self.labelResolutionY.setObjectName("labelResolutionY")
        self.horizontalLayout.addWidget(self.labelResolutionY)
        self.lineEditResolutionY = QtWidgets.QLineEdit(self.frameResolution)
        self.lineEditResolutionY.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lineEditResolutionY.setFont(font)
        self.lineEditResolutionY.setStyleSheet("QLineEdit\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(50, 50, 50);\n"
"}")
        self.lineEditResolutionY.setObjectName("lineEditResolutionY")
        self.horizontalLayout.addWidget(self.lineEditResolutionY)
        self.verticalLayout_2.addWidget(self.frameResolution)
        self.frameFPS = QtWidgets.QFrame(self.frameInput)
        self.frameFPS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFPS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFPS.setObjectName("frameFPS")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameFPS)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelFPS = QtWidgets.QLabel(self.frameFPS)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.labelFPS.setFont(font)
        self.labelFPS.setStyleSheet("color:  rgb(200, 200, 200);")
        self.labelFPS.setObjectName("labelFPS")
        self.horizontalLayout_2.addWidget(self.labelFPS)
        self.lineEditFPS = QtWidgets.QLineEdit(self.frameFPS)
        self.lineEditFPS.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lineEditFPS.setFont(font)
        self.lineEditFPS.setStyleSheet("QLineEdit\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(50, 50, 50);\n"
"}")
        self.lineEditFPS.setObjectName("lineEditFPS")
        self.horizontalLayout_2.addWidget(self.lineEditFPS)
        self.verticalLayout_2.addWidget(self.frameFPS)
        self.verticalLayout.addWidget(self.frameInput)
        self.frameInformations = QtWidgets.QFrame(self.frameAll)
        self.frameInformations.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frameInformations.setStyleSheet("")
        self.frameInformations.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameInformations.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInformations.setObjectName("frameInformations")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameInformations)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 18)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelInformations = QtWidgets.QLabel(self.frameInformations)
        self.labelInformations.setMinimumSize(QtCore.QSize(0, 50))
        self.labelInformations.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.labelInformations.setFont(font)
        self.labelInformations.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.labelInformations.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(50, 50, 50);\n"
"}")
        self.labelInformations.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelInformations.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelInformations.setWordWrap(True)
        self.labelInformations.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelInformations.setObjectName("labelInformations")
        self.verticalLayout_4.addWidget(self.labelInformations)
        self.verticalLayout.addWidget(self.frameInformations)
        self.frameChoice = QtWidgets.QFrame(self.frameAll)
        self.frameChoice.setMinimumSize(QtCore.QSize(0, 50))
        self.frameChoice.setMaximumSize(QtCore.QSize(16777215, 33))
        self.frameChoice.setStyleSheet("    background-color: rgb(50, 50, 50);")
        self.frameChoice.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameChoice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameChoice.setLineWidth(0)
        self.frameChoice.setObjectName("frameChoice")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frameChoice)
        self.horizontalLayout_9.setContentsMargins(9, 0, 9, 9)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(10, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.labelSeparator = QtWidgets.QLabel(self.frameChoice)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSeparator.setFont(font)
        self.labelSeparator.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelSeparator.setText("")
        self.labelSeparator.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSeparator.setObjectName("labelSeparator")
        self.horizontalLayout_9.addWidget(self.labelSeparator)
        self.buttonOk = QtWidgets.QPushButton(self.frameChoice)
        self.buttonOk.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.buttonOk.setFont(font)
        self.buttonOk.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        self.buttonOk.setObjectName("buttonOk")
        self.horizontalLayout_9.addWidget(self.buttonOk)
        spacerItem2 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.buttonCancel = QtWidgets.QPushButton(self.frameChoice)
        self.buttonCancel.setMinimumSize(QtCore.QSize(0, 20))
        self.buttonCancel.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.buttonCancel.setFont(font)
        self.buttonCancel.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout_9.addWidget(self.buttonCancel)
        self.verticalLayout.addWidget(self.frameChoice)
        self.verticalLayout_3.addWidget(self.frameAll)

        self.retranslateUi(CreateProject)
        QtCore.QMetaObject.connectSlotsByName(CreateProject)

    def retranslateUi(self, CreateProject):
        _translate = QtCore.QCoreApplication.translate
        CreateProject.setWindowTitle(_translate("CreateProject", "Dialog"))
        self.labelCreateProject.setText(_translate("CreateProject", "Create Project"))
        self.lineEditInput.setText(_translate("CreateProject", "pro"))
        self.labelResolutionX.setText(_translate("CreateProject", "Res. X"))
        self.lineEditResolutionX.setText(_translate("CreateProject", "1920"))
        self.labelResolutionY.setText(_translate("CreateProject", "Res. Y"))
        self.lineEditResolutionY.setText(_translate("CreateProject", "1080"))
        self.labelFPS.setText(_translate("CreateProject", "FPS    "))
        self.lineEditFPS.setText(_translate("CreateProject", "24"))
        self.labelInformations.setText(_translate("CreateProject", ">>> Terminal - No more than 3 characters! - Example: abc, pro"))
        self.buttonOk.setText(_translate("CreateProject", "OK"))
        self.buttonCancel.setText(_translate("CreateProject", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateProject = QtWidgets.QDialog()
    ui = Ui_CreateProject()
    ui.setupUi(CreateProject)
    CreateProject.show()
    sys.exit(app.exec_())
