# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Valen\Documents\PROJECTS\.pipeline\all\ui/cioxo_houdini_projectManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence,
                           QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import ui_cioxo_QtResources_rc


class Ui_Houdini_projectManager(object):
    def setupUi(self, Houdini_projectManager):
        Houdini_projectManager.setObjectName("Houdini_projectManager")
        Houdini_projectManager.resize(700, 700)
        Houdini_projectManager.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(Houdini_projectManager)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameDropShadow = QtWidgets.QFrame(self.centralWidget)
        self.frameDropShadow.setStyleSheet("QFrame{\n"
"    color: rgb(180, 180, 180);\n"
"    background-color:rgb(27, 27, 27);    \n"
"    border-radius: 5px;\n"
"}")
        self.frameDropShadow.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameDropShadow.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameDropShadow.setObjectName("frameDropShadow")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameDropShadow)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameTitleBar = QtWidgets.QFrame(self.frameDropShadow)
        self.frameTitleBar.setMinimumSize(QtCore.QSize(0, 30))
        self.frameTitleBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frameTitleBar.setStyleSheet("border-radius: 0px;")
        self.frameTitleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTitleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitleBar.setObjectName("frameTitleBar")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frameTitleBar)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.pushButtonTitleBar = QtWidgets.QPushButton(self.frameTitleBar)
        self.pushButtonTitleBar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/graphics/icons/terminal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonTitleBar.setIcon(icon)
        self.pushButtonTitleBar.setIconSize(QtCore.QSize(16, 16))
        self.pushButtonTitleBar.setObjectName("pushButtonTitleBar")
        self.horizontalLayout_13.addWidget(self.pushButtonTitleBar)
        self.labelTitleBar = QtWidgets.QLabel(self.frameTitleBar)
        self.labelTitleBar.setMinimumSize(QtCore.QSize(40, 0))
        self.labelTitleBar.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.labelTitleBar.setFont(font)
        self.labelTitleBar.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitleBar.setObjectName("labelTitleBar")
        self.horizontalLayout_13.addWidget(self.labelTitleBar)
        self.labelSpacer = QtWidgets.QLabel(self.frameTitleBar)
        self.labelSpacer.setMaximumSize(QtCore.QSize(5, 16777215))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        self.labelSpacer.setFont(font)
        self.labelSpacer.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSpacer.setObjectName("labelSpacer")
        self.horizontalLayout_13.addWidget(self.labelSpacer)
        self.labelVersionTitleBar = QtWidgets.QLabel(self.frameTitleBar)
        self.labelVersionTitleBar.setMinimumSize(QtCore.QSize(40, 0))
        self.labelVersionTitleBar.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.labelVersionTitleBar.setFont(font)
        self.labelVersionTitleBar.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVersionTitleBar.setObjectName("labelVersionTitleBar")
        self.horizontalLayout_13.addWidget(self.labelVersionTitleBar)
        spacerItem1 = QtWidgets.QSpacerItem(500, 4, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frameTitleBar)
        self.frameBanner = QtWidgets.QFrame(self.frameDropShadow)
        self.frameBanner.setStyleSheet("")
        self.frameBanner.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBanner.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameBanner.setObjectName("frameBanner")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frameBanner)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frameTitle = QtWidgets.QFrame(self.frameBanner)
        self.frameTitle.setMinimumSize(QtCore.QSize(0, 50))
        self.frameTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frameTitle.setStyleSheet("border-top-left-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;")
        self.frameTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitle.setObjectName("frameTitle")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameTitle)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameLabelTitle = QtWidgets.QFrame(self.frameTitle)
        self.frameLabelTitle.setStyleSheet("QFrame\n"
"{\n"
"    background-color:rgb(50, 50, 50);\n"
"}\n"
"")
        self.frameLabelTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameLabelTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLabelTitle.setObjectName("frameLabelTitle")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameLabelTitle)
        self.horizontalLayout_3.setContentsMargins(-1, -1, 18, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelTitleLogo = QtWidgets.QLabel(self.frameLabelTitle)
        self.labelTitleLogo.setMinimumSize(QtCore.QSize(32, 32))
        self.labelTitleLogo.setMaximumSize(QtCore.QSize(32, 32))
        self.labelTitleLogo.setText("")
        self.labelTitleLogo.setPixmap(QtGui.QPixmap(":/logos/graphics/logos/cioxoLogo_24.png"))
        self.labelTitleLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitleLogo.setObjectName("labelTitleLogo")
        self.horizontalLayout_3.addWidget(self.labelTitleLogo)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.labelTitle = QtWidgets.QLabel(self.frameLabelTitle)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout_3.addWidget(self.labelTitle)
        self.horizontalLayout.addWidget(self.frameLabelTitle)
        self.verticalLayout_8.addWidget(self.frameTitle)
        self.verticalLayout_2.addWidget(self.frameBanner)
        self.frameContent = QtWidgets.QFrame(self.frameDropShadow)
        self.frameContent.setStyleSheet("background-color:rgb(27, 27, 27);")
        self.frameContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameContent.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameContent.setObjectName("frameContent")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameContent)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameContentSub = QtWidgets.QFrame(self.frameContent)
        self.frameContentSub.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameContentSub.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameContentSub.setObjectName("frameContentSub")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameContentSub)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameTabs = QtWidgets.QFrame(self.frameContentSub)
        self.frameTabs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameTabs.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameTabs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTabs.setObjectName("frameTabs")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frameTabs)
        self.horizontalLayout_8.setContentsMargins(1, 0, 9, 9)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frameTabsSub = QtWidgets.QFrame(self.frameTabs)
        self.frameTabsSub.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameTabsSub.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameTabsSub.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTabsSub.setObjectName("frameTabsSub")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameTabsSub)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frameLineFiles = QtWidgets.QFrame(self.frameTabsSub)
        self.frameLineFiles.setStyleSheet("")
        self.frameLineFiles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLineFiles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLineFiles.setObjectName("frameLineFiles")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frameLineFiles)
        self.horizontalLayout_23.setContentsMargins(-1, 18, -1, 9)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.labelWelcomeFiles = QtWidgets.QLabel(self.frameLineFiles)
        self.labelWelcomeFiles.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelWelcomeFiles.setFont(font)
        self.labelWelcomeFiles.setStyleSheet("color:white;")
        self.labelWelcomeFiles.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelWelcomeFiles.setObjectName("labelWelcomeFiles")
        self.horizontalLayout_23.addWidget(self.labelWelcomeFiles)
        self.labelLineTitleFiles = QtWidgets.QLabel(self.frameLineFiles)
        self.labelLineTitleFiles.setMaximumSize(QtCore.QSize(16777215, 0))
        self.labelLineTitleFiles.setStyleSheet("border-color: rgb(180, 180, 180);\n"
"border-style:solid;\n"
"border-radius: 5px;\n"
"border-width: 1px;")
        self.labelLineTitleFiles.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelLineTitleFiles.setText("")
        self.labelLineTitleFiles.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLineTitleFiles.setObjectName("labelLineTitleFiles")
        self.horizontalLayout_23.addWidget(self.labelLineTitleFiles)
        self.verticalLayout_5.addWidget(self.frameLineFiles)
        self.frameContentFiles = QtWidgets.QFrame(self.frameTabsSub)
        self.frameContentFiles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameContentFiles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameContentFiles.setObjectName("frameContentFiles")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frameContentFiles)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frameListFiles = QtWidgets.QFrame(self.frameContentFiles)
        self.frameListFiles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameListFiles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameListFiles.setObjectName("frameListFiles")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frameListFiles)
        self.verticalLayout_12.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_12.setSpacing(9)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frameTitleFiles = QtWidgets.QFrame(self.frameListFiles)
        self.frameTitleFiles.setMinimumSize(QtCore.QSize(0, 33))
        self.frameTitleFiles.setMaximumSize(QtCore.QSize(16777215, 33))
        self.frameTitleFiles.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameTitleFiles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitleFiles.setObjectName("frameTitleFiles")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frameTitleFiles)
        self.horizontalLayout_17.setContentsMargins(0, -1, 0, 3)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem3 = QtWidgets.QSpacerItem(10, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.labelFiles = QtWidgets.QLabel(self.frameTitleFiles)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelFiles.setFont(font)
        self.labelFiles.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelFiles.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFiles.setObjectName("labelFiles")
        self.horizontalLayout_17.addWidget(self.labelFiles)
        spacerItem4 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.buttonCreateFiles = QtWidgets.QPushButton(self.frameTitleFiles)
        self.buttonCreateFiles.setMinimumSize(QtCore.QSize(0, 20))
        self.buttonCreateFiles.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.buttonCreateFiles.setFont(font)
        self.buttonCreateFiles.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/graphics/icons/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCreateFiles.setIcon(icon1)
        self.buttonCreateFiles.setObjectName("buttonCreateFiles")
        self.horizontalLayout_17.addWidget(self.buttonCreateFiles)
        spacerItem5 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem5)
        self.buttonReloadFiles = QtWidgets.QPushButton(self.frameTitleFiles)
        self.buttonReloadFiles.setMinimumSize(QtCore.QSize(50, 20))
        self.buttonReloadFiles.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.buttonReloadFiles.setFont(font)
        self.buttonReloadFiles.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        self.buttonReloadFiles.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/graphics/icons/refreshCw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonReloadFiles.setIcon(icon2)
        self.buttonReloadFiles.setObjectName("buttonReloadFiles")
        self.horizontalLayout_17.addWidget(self.buttonReloadFiles)
        self.verticalLayout_12.addWidget(self.frameTitleFiles)
        self.listFiles = QtWidgets.QListWidget(self.frameListFiles)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.listFiles.setFont(font)
        self.listFiles.setStyleSheet("QListWidget\n"
"{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(180, 180, 180);\n"
"    border-radius:5px;\n"
"}\n"
"QListWidget:item:hover:!pressed\n"
"{\n"
"    background :  rgb(70, 70, 70);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(50, 50, 50);\n"
"    width: 8px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(130, 130, 130);\n"
"    min-height: 30px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 0px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 0px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.listFiles.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listFiles.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listFiles.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listFiles.setViewMode(QtWidgets.QListView.ListMode)
        self.listFiles.setObjectName("listFiles")
        self.verticalLayout_12.addWidget(self.listFiles)
        self.horizontalLayout_18.addWidget(self.frameListFiles)
        self.frameRightSideFiles = QtWidgets.QFrame(self.frameContentFiles)
        self.frameRightSideFiles.setMaximumSize(QtCore.QSize(259, 16777215))
        self.frameRightSideFiles.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameRightSideFiles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRightSideFiles.setObjectName("frameRightSideFiles")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frameRightSideFiles)
        self.verticalLayout_11.setContentsMargins(3, 2, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem6 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem6)
        self.labelThumbnailFiles = QtWidgets.QLabel(self.frameRightSideFiles)
        self.labelThumbnailFiles.setMinimumSize(QtCore.QSize(256, 144))
        self.labelThumbnailFiles.setMaximumSize(QtCore.QSize(256, 144))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.labelThumbnailFiles.setFont(font)
        self.labelThumbnailFiles.setStyleSheet("QLabel\n"
"{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;    \n"
"    border-width: 1px;\n"
"    border-radius: 0px;\n"
"    border-color: rgb(50, 50, 50);\n"
"}\n"
"")
        self.labelThumbnailFiles.setAlignment(QtCore.Qt.AlignCenter)
        self.labelThumbnailFiles.setObjectName("labelThumbnailFiles")
        self.verticalLayout_11.addWidget(self.labelThumbnailFiles)
        self.frameFunctionsThumbnailFiles = QtWidgets.QFrame(self.frameRightSideFiles)
        self.frameFunctionsThumbnailFiles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFunctionsThumbnailFiles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFunctionsThumbnailFiles.setObjectName("frameFunctionsThumbnailFiles")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frameFunctionsThumbnailFiles)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.buttonDeleteThumbnailFiles = QtWidgets.QPushButton(self.frameFunctionsThumbnailFiles)
        self.buttonDeleteThumbnailFiles.setMinimumSize(QtCore.QSize(25, 25))
        self.buttonDeleteThumbnailFiles.setMaximumSize(QtCore.QSize(25, 25))
        self.buttonDeleteThumbnailFiles.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        self.buttonDeleteThumbnailFiles.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/graphics/icons/trash02.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDeleteThumbnailFiles.setIcon(icon3)
        self.buttonDeleteThumbnailFiles.setObjectName("buttonDeleteThumbnailFiles")
        self.horizontalLayout_16.addWidget(self.buttonDeleteThumbnailFiles)
        self.buttonRefreshThumbnailFiles = QtWidgets.QPushButton(self.frameFunctionsThumbnailFiles)
        self.buttonRefreshThumbnailFiles.setMinimumSize(QtCore.QSize(25, 25))
        self.buttonRefreshThumbnailFiles.setMaximumSize(QtCore.QSize(25, 25))
        self.buttonRefreshThumbnailFiles.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        self.buttonRefreshThumbnailFiles.setText("")
        self.buttonRefreshThumbnailFiles.setIcon(icon2)
        self.buttonRefreshThumbnailFiles.setObjectName("buttonRefreshThumbnailFiles")
        self.horizontalLayout_16.addWidget(self.buttonRefreshThumbnailFiles)
        self.buttonChargeThumbnailFiles = QtWidgets.QPushButton(self.frameFunctionsThumbnailFiles)
        self.buttonChargeThumbnailFiles.setMinimumSize(QtCore.QSize(25, 25))
        self.buttonChargeThumbnailFiles.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.buttonChargeThumbnailFiles.setFont(font)
        self.buttonChargeThumbnailFiles.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        self.buttonChargeThumbnailFiles.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/graphics/icons/image.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonChargeThumbnailFiles.setIcon(icon4)
        self.buttonChargeThumbnailFiles.setObjectName("buttonChargeThumbnailFiles")
        self.horizontalLayout_16.addWidget(self.buttonChargeThumbnailFiles)
        self.verticalLayout_11.addWidget(self.frameFunctionsThumbnailFiles)
        self.labelLineFiles = QtWidgets.QLabel(self.frameRightSideFiles)
        self.labelLineFiles.setMaximumSize(QtCore.QSize(16777215, 1))
        self.labelLineFiles.setStyleSheet("border-color: rgb(180, 180, 180);\n"
"border-style:solid;\n"
"border-radius: 5px;\n"
"border-width: 1px;")
        self.labelLineFiles.setText("")
        self.labelLineFiles.setObjectName("labelLineFiles")
        self.verticalLayout_11.addWidget(self.labelLineFiles)
        self.labelCommentFiles = QtWidgets.QLabel(self.frameRightSideFiles)
        self.labelCommentFiles.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.labelCommentFiles.setFont(font)
        self.labelCommentFiles.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelCommentFiles.setStyleSheet("    background-color: rgb(50, 50, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"    border-color: rgb(50, 50, 50);")
        self.labelCommentFiles.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelCommentFiles.setWordWrap(True)
        self.labelCommentFiles.setObjectName("labelCommentFiles")
        self.verticalLayout_11.addWidget(self.labelCommentFiles)
        self.buttonOpenFiles = QtWidgets.QPushButton(self.frameRightSideFiles)
        self.buttonOpenFiles.setMinimumSize(QtCore.QSize(0, 25))
        self.buttonOpenFiles.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.buttonOpenFiles.setFont(font)
        self.buttonOpenFiles.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/graphics/icons/arrowUpRight.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonOpenFiles.setIcon(icon5)
        self.buttonOpenFiles.setObjectName("buttonOpenFiles")
        self.verticalLayout_11.addWidget(self.buttonOpenFiles)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.layoutDirectoryFiles = QtWidgets.QHBoxLayout()
        self.layoutDirectoryFiles.setObjectName("layoutDirectoryFiles")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutDirectoryFiles.addItem(spacerItem9)
        self.buttonDirectoryFiles = QtWidgets.QPushButton(self.frameRightSideFiles)
        self.buttonDirectoryFiles.setMinimumSize(QtCore.QSize(131, 25))
        self.buttonDirectoryFiles.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.buttonDirectoryFiles.setFont(font)
        self.buttonDirectoryFiles.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/graphics/icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDirectoryFiles.setIcon(icon6)
        self.buttonDirectoryFiles.setObjectName("buttonDirectoryFiles")
        self.layoutDirectoryFiles.addWidget(self.buttonDirectoryFiles)
        self.verticalLayout_11.addLayout(self.layoutDirectoryFiles)
        self.horizontalLayout_18.addWidget(self.frameRightSideFiles)
        self.verticalLayout_5.addWidget(self.frameContentFiles)
        self.frameInformations = QtWidgets.QFrame(self.frameTabsSub)
        self.frameInformations.setStyleSheet("")
        self.frameInformations.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameInformations.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameInformations.setLineWidth(0)
        self.frameInformations.setObjectName("frameInformations")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameInformations)
        self.verticalLayout_4.setContentsMargins(8, 10, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelInformations = QtWidgets.QLabel(self.frameInformations)
        self.labelInformations.setMinimumSize(QtCore.QSize(0, 50))
        self.labelInformations.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.labelInformations.setFont(font)
        self.labelInformations.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.labelInformations.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(50, 50, 50);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 255, 255);\n"
"    selection-background-color: lightgray;\n"
"}")
        self.labelInformations.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelInformations.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelInformations.setWordWrap(True)
        self.labelInformations.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelInformations.setObjectName("labelInformations")
        self.verticalLayout_4.addWidget(self.labelInformations)
        self.verticalLayout_5.addWidget(self.frameInformations)
        self.horizontalLayout_8.addWidget(self.frameTabsSub)
        self.verticalLayout_6.addWidget(self.frameTabs)
        self.verticalLayout_3.addWidget(self.frameContentSub)
        self.verticalLayout_2.addWidget(self.frameContent)
        self.frameCredit = QtWidgets.QFrame(self.frameDropShadow)
        self.frameCredit.setMinimumSize(QtCore.QSize(0, 30))
        self.frameCredit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frameCredit.setStyleSheet("QFrame\n"
"{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(27, 27, 27);\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"}\n"
"")
        self.frameCredit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameCredit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCredit.setObjectName("frameCredit")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameCredit)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameLabelCredit = QtWidgets.QFrame(self.frameCredit)
        self.frameLabelCredit.setMinimumSize(QtCore.QSize(0, 0))
        self.frameLabelCredit.setStyleSheet("")
        self.frameLabelCredit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameLabelCredit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLabelCredit.setObjectName("frameLabelCredit")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frameLabelCredit)
        self.horizontalLayout_4.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelCredits = QtWidgets.QLabel(self.frameLabelCredit)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.labelCredits.setFont(font)
        self.labelCredits.setStyleSheet("color: rgba(255, 255, 255, 128);")
        self.labelCredits.setObjectName("labelCredits")
        self.horizontalLayout_4.addWidget(self.labelCredits)
        self.labelVersion = QtWidgets.QLabel(self.frameLabelCredit)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.labelVersion.setFont(font)
        self.labelVersion.setStyleSheet("color: rgba(255, 255, 255, 128);")
        self.labelVersion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelVersion.setObjectName("labelVersion")
        self.horizontalLayout_4.addWidget(self.labelVersion)
        self.horizontalLayout_2.addWidget(self.frameLabelCredit)
        self.verticalLayout_2.addWidget(self.frameCredit)
        self.verticalLayout.addWidget(self.frameDropShadow)
        Houdini_projectManager.setCentralWidget(self.centralWidget)
        self.actionAbout = QtWidgets.QAction(Houdini_projectManager)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(Houdini_projectManager)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(Houdini_projectManager)
        QtCore.QMetaObject.connectSlotsByName(Houdini_projectManager)

    def retranslateUi(self, Houdini_projectManager):
        _translate = QtCore.QCoreApplication.translate
        Houdini_projectManager.setWindowTitle(_translate("Houdini_projectManager", "Cioxo - Project Manager"))
        self.labelTitleBar.setText(_translate("Houdini_projectManager", "Cioxo"))
        self.labelSpacer.setText(_translate("Houdini_projectManager", "-"))
        self.labelVersionTitleBar.setText(_translate("Houdini_projectManager", "v1.0.0"))
        self.labelTitle.setText(_translate("Houdini_projectManager", "Cioxo"))
        self.labelWelcomeFiles.setText(_translate("Houdini_projectManager", "Project"))
        self.labelFiles.setText(_translate("Houdini_projectManager", "Files"))
        self.buttonCreateFiles.setText(_translate("Houdini_projectManager", "Create New "))
        self.listFiles.setSortingEnabled(False)
        self.labelThumbnailFiles.setText(_translate("Houdini_projectManager", "Thumbnail"))
        self.labelCommentFiles.setText(_translate("Houdini_projectManager", "Comment"))
        self.buttonOpenFiles.setText(_translate("Houdini_projectManager", "Open"))
        self.buttonDirectoryFiles.setText(_translate("Houdini_projectManager", "Directory"))
        self.labelInformations.setText(_translate("Houdini_projectManager", ">>> Terminal"))
        self.labelCredits.setText(_translate("Houdini_projectManager", "© 2020-2021 Valentin Beaumont"))
        self.labelVersion.setText(_translate("Houdini_projectManager", "v1.0.0"))
        self.actionAbout.setText(_translate("Houdini_projectManager", "v1.0.0 - © 2020-2021 Valentin Beaumont"))
        self.actionExit.setText(_translate("Houdini_projectManager", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Houdini_projectManager = QtWidgets.QMainWindow()
    ui = Ui_Houdini_projectManager()
    ui.setupUi(Houdini_projectManager)
    Houdini_projectManager.show()
    sys.exit(app.exec_())
