# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Valen\Documents\PROJECTS\.pipeline\all\ui\splashScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence,
                           QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import ui_cioxo_QtResources_rc



class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(680, 400)
        SplashScreen.setMinimumSize(QtCore.QSize(680, 400))
        SplashScreen.setMaximumSize(QtCore.QSize(680, 400))
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameDropShadow = QtWidgets.QFrame(self.centralwidget)
        self.frameDropShadow.setStyleSheet("QFrame{\n"
"    color: rgb(180, 180, 180);\n"
"    background-color:rgb(27, 27, 27);\n"
"    border-radius:5px;\n"
"}")
        self.frameDropShadow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDropShadow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDropShadow.setObjectName("frameDropShadow")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameDropShadow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameLeft = QtWidgets.QFrame(self.frameDropShadow)
        self.frameLeft.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frameLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLeft.setObjectName("frameLeft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameLeft)
        self.verticalLayout_2.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelLogo = QtWidgets.QLabel(self.frameLeft)
        self.labelLogo.setMinimumSize(QtCore.QSize(33, 33))
        self.labelLogo.setMaximumSize(QtCore.QSize(33, 33))
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap(":/logos/graphics/logos/cioxoLogo_32.png"))
        self.labelLogo.setObjectName("labelLogo")
        self.verticalLayout_2.addWidget(self.labelLogo)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.labelPipeline = QtWidgets.QLabel(self.frameLeft)
        self.labelPipeline.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.labelPipeline.setFont(font)
        self.labelPipeline.setObjectName("labelPipeline")
        self.verticalLayout_2.addWidget(self.labelPipeline)
        spacerItem1 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.labelCioxo = QtWidgets.QLabel(self.frameLeft)
        self.labelCioxo.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(18)
        self.labelCioxo.setFont(font)
        self.labelCioxo.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelCioxo.setObjectName("labelCioxo")
        self.verticalLayout_2.addWidget(self.labelCioxo)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.labelCopyright = QtWidgets.QLabel(self.frameLeft)
        self.labelCopyright.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.labelCopyright.setFont(font)
        self.labelCopyright.setObjectName("labelCopyright")
        self.verticalLayout_2.addWidget(self.labelCopyright)
        self.labelAllRights = QtWidgets.QLabel(self.frameLeft)
        self.labelAllRights.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.labelAllRights.setFont(font)
        self.labelAllRights.setObjectName("labelAllRights")
        self.verticalLayout_2.addWidget(self.labelAllRights)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.labelLoading = QtWidgets.QLabel(self.frameLeft)
        self.labelLoading.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.labelLoading.setFont(font)
        self.labelLoading.setObjectName("labelLoading")
        self.verticalLayout_2.addWidget(self.labelLoading)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.progressBarLoading = QtWidgets.QProgressBar(self.frameLeft)
        self.progressBarLoading.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.progressBarLoading.setFont(font)
        self.progressBarLoading.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(175, 175, 175);\n"
"    color:rgb(255, 255, 255);\n"
"    border-style:none;\n"
"    border-radius:5px;\n"
"    text-align:center;    \n"
"}\n"
"QProgressBar:chunk{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.progressBarLoading.setProperty("value", 24)
        self.progressBarLoading.setObjectName("progressBarLoading")
        self.verticalLayout_2.addWidget(self.progressBarLoading)
        spacerItem5 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.labelText = QtWidgets.QLabel(self.frameLeft)
        self.labelText.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.labelText.setFont(font)
        self.labelText.setWordWrap(True)
        self.labelText.setObjectName("labelText")
        self.verticalLayout_2.addWidget(self.labelText)
        self.labelVersion = QtWidgets.QLabel(self.frameLeft)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        self.labelVersion.setFont(font)
        self.labelVersion.setStyleSheet("color: rgb(130, 130, 130);")
        self.labelVersion.setObjectName("labelVersion")
        self.verticalLayout_2.addWidget(self.labelVersion)
        self.horizontalLayout.addWidget(self.frameLeft)
        self.frameRight = QtWidgets.QFrame(self.frameDropShadow)
        self.frameRight.setMaximumSize(QtCore.QSize(470, 400))
        self.frameRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRight.setObjectName("frameRight")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameRight)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelArtwork = QtWidgets.QLabel(self.frameRight)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.labelArtwork.setFont(font)
        self.labelArtwork.setText("")
        self.labelArtwork.setPixmap(QtGui.QPixmap(":/images/graphics/images/splashScreen01_v005.png"))
        self.labelArtwork.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.labelArtwork.setObjectName("labelArtwork")
        self.verticalLayout_3.addWidget(self.labelArtwork)
        self.horizontalLayout.addWidget(self.frameRight)
        self.horizontalLayout_2.addWidget(self.frameDropShadow)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.labelPipeline.setText(_translate("SplashScreen", "Pipeline"))
        self.labelCioxo.setText(_translate("SplashScreen", "Cioxo"))
        self.labelCopyright.setText(_translate("SplashScreen", "© 2020-2021 Valentin Beaumont."))
        self.labelAllRights.setText(_translate("SplashScreen", "All rights reserved."))
        self.labelLoading.setText(_translate("SplashScreen", "Loading  Preferences..."))
        self.labelText.setText(_translate("SplashScreen", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco."))
        self.labelVersion.setText(_translate("SplashScreen", "v1.0.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
