# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Valen\Documents\PROJECTS\.pipeline\all\ui\cioxo_splashScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence,
                           QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import ui_cioxo_QtResources_rc


class Ui_cioxo_splashScreen(object):
    def setupUi(self, cioxo_splashScreen):
        cioxo_splashScreen.setObjectName("cioxo_splashScreen")
        cioxo_splashScreen.resize(680, 400)
        cioxo_splashScreen.setMinimumSize(QtCore.QSize(680, 400))
        cioxo_splashScreen.setMaximumSize(QtCore.QSize(680, 400))
        self.central_widget = QtWidgets.QWidget(cioxo_splashScreen)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_dropShadow = QtWidgets.QFrame(self.central_widget)
        self.frame_dropShadow.setStyleSheet("QFrame{\n"
"    color: rgb(180, 180, 180);\n"
"    background-color:rgb(27, 27, 27);\n"
"    border-radius:5px;\n"
"}")
        self.frame_dropShadow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dropShadow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dropShadow.setObjectName("frame_dropShadow")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_dropShadow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left = QtWidgets.QFrame(self.frame_dropShadow)
        self.frame_left.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_2.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_logo = QtWidgets.QLabel(self.frame_left)
        self.label_logo.setMinimumSize(QtCore.QSize(33, 33))
        self.label_logo.setMaximumSize(QtCore.QSize(33, 33))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap(":/logos/graphics/logos/cioxoLogo_32.png"))
        self.label_logo.setObjectName("label_logo")
        self.verticalLayout_2.addWidget(self.label_logo)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_pipeline = QtWidgets.QLabel(self.frame_left)
        self.label_pipeline.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_pipeline.setFont(font)
        self.label_pipeline.setObjectName("label_pipeline")
        self.verticalLayout_2.addWidget(self.label_pipeline)
        spacerItem1 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_cioxo = QtWidgets.QLabel(self.frame_left)
        self.label_cioxo.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(18)
        self.label_cioxo.setFont(font)
        self.label_cioxo.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_cioxo.setObjectName("label_cioxo")
        self.verticalLayout_2.addWidget(self.label_cioxo)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_copyright = QtWidgets.QLabel(self.frame_left)
        self.label_copyright.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_copyright.setFont(font)
        self.label_copyright.setObjectName("label_copyright")
        self.verticalLayout_2.addWidget(self.label_copyright)
        self.label_allRights = QtWidgets.QLabel(self.frame_left)
        self.label_allRights.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_allRights.setFont(font)
        self.label_allRights.setObjectName("label_allRights")
        self.verticalLayout_2.addWidget(self.label_allRights)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_loading = QtWidgets.QLabel(self.frame_left)
        self.label_loading.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_loading.setFont(font)
        self.label_loading.setObjectName("label_loading")
        self.verticalLayout_2.addWidget(self.label_loading)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.progressBar_loading = QtWidgets.QProgressBar(self.frame_left)
        self.progressBar_loading.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.progressBar_loading.setFont(font)
        self.progressBar_loading.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(175, 175, 175);\n"
"    color:rgb(255, 255, 255);\n"
"    border-style:none;\n"
"    border-radius:5px;\n"
"    text-align:center;    \n"
"}\n"
"QProgressBar:chunk{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.progressBar_loading.setProperty("value", 24)
        self.progressBar_loading.setObjectName("progressBar_loading")
        self.verticalLayout_2.addWidget(self.progressBar_loading)
        spacerItem5 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_text = QtWidgets.QLabel(self.frame_left)
        self.label_text.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_text.setFont(font)
        self.label_text.setWordWrap(True)
        self.label_text.setObjectName("label_text")
        self.verticalLayout_2.addWidget(self.label_text)
        self.label_version = QtWidgets.QLabel(self.frame_left)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(130, 130, 130);")
        self.label_version.setObjectName("label_version")
        self.verticalLayout_2.addWidget(self.label_version)
        self.horizontalLayout.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(self.frame_dropShadow)
        self.frame_right.setMaximumSize(QtCore.QSize(470, 400))
        self.frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_artwork = QtWidgets.QLabel(self.frame_right)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_artwork.setFont(font)
        self.label_artwork.setText("")
        self.label_artwork.setPixmap(QtGui.QPixmap(":/images/graphics/images/splashScreen01_v005.png"))
        self.label_artwork.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_artwork.setObjectName("label_artwork")
        self.verticalLayout_3.addWidget(self.label_artwork)
        self.horizontalLayout.addWidget(self.frame_right)
        self.horizontalLayout_2.addWidget(self.frame_dropShadow)
        cioxo_splashScreen.setCentralWidget(self.central_widget)

        self.retranslateUi(cioxo_splashScreen)
        QtCore.QMetaObject.connectSlotsByName(cioxo_splashScreen)

    def retranslateUi(self, cioxo_splashScreen):
        _translate = QtCore.QCoreApplication.translate
        cioxo_splashScreen.setWindowTitle(_translate("cioxo_splashScreen", "MainWindow"))
        self.label_pipeline.setText(_translate("cioxo_splashScreen", "Pipeline"))
        self.label_cioxo.setText(_translate("cioxo_splashScreen", "Cioxo"))
        self.label_copyright.setText(_translate("cioxo_splashScreen", "© 2020-2021 Valentin Beaumont."))
        self.label_allRights.setText(_translate("cioxo_splashScreen", "All rights reserved."))
        self.label_loading.setText(_translate("cioxo_splashScreen", "Loading  Preferences..."))
        self.label_text.setText(_translate("cioxo_splashScreen", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco."))
        self.label_version.setText(_translate("cioxo_splashScreen", "v1.0.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cioxo_splashScreen = QtWidgets.QMainWindow()
    ui = Ui_cioxo_splashScreen()
    ui.setupUi(cioxo_splashScreen)
    cioxo_splashScreen.show()
    sys.exit(app.exec_())
