# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Valen\Documents\PROJECTS\.pipeline\all\ui\cioxo_houdini_openWorkspace.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence,
                           QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import ui_cioxo_QtResources_rc


class Ui_cioxo_houdini_openWorkspace(object):
    def setupUi(self, cioxo_houdini_openWorkspace):
        cioxo_houdini_openWorkspace.setObjectName("cioxo_houdini_openWorkspace")
        cioxo_houdini_openWorkspace.resize(700, 684)
        cioxo_houdini_openWorkspace.setStyleSheet("")
        self.central_widget = QtWidgets.QWidget(cioxo_houdini_openWorkspace)
        self.central_widget.setStyleSheet("")
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_dropShadow = QtWidgets.QFrame(self.central_widget)
        self.frame_dropShadow.setStyleSheet("QFrame{\n"
"    color: rgb(180, 180, 180);\n"
"    background-color:rgb(27, 27, 27);    \n"
"    border-radius: 5px;\n"
"}")
        self.frame_dropShadow.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_dropShadow.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_dropShadow.setObjectName("frame_dropShadow")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_dropShadow)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_banner = QtWidgets.QFrame(self.frame_dropShadow)
        self.frame_banner.setStyleSheet("")
        self.frame_banner.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_banner.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_banner.setObjectName("frame_banner")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_banner)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_2.addWidget(self.frame_banner)
        self.frame_content = QtWidgets.QFrame(self.frame_dropShadow)
        self.frame_content.setStyleSheet("background-color:rgb(27, 27, 27);")
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_contentSub = QtWidgets.QFrame(self.frame_content)
        self.frame_contentSub.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contentSub.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contentSub.setObjectName("frame_contentSub")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_contentSub)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_tabs = QtWidgets.QFrame(self.frame_contentSub)
        self.frame_tabs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_tabs.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tabs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabs.setObjectName("frame_tabs")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_tabs)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_tabsSub = QtWidgets.QFrame(self.frame_tabs)
        self.frame_tabsSub.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_tabsSub.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tabsSub.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabsSub.setObjectName("frame_tabsSub")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_tabsSub)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_title = QtWidgets.QFrame(self.frame_tabsSub)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_title.setStyleSheet("")
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_title.setLineWidth(0)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_23.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_welcomeFiles = QtWidgets.QLabel(self.frame_title)
        self.label_welcomeFiles.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_welcomeFiles.setFont(font)
        self.label_welcomeFiles.setStyleSheet("color:white;")
        self.label_welcomeFiles.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_welcomeFiles.setObjectName("label_welcomeFiles")
        self.horizontalLayout_23.addWidget(self.label_welcomeFiles)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.verticalLayout_5.addWidget(self.frame_title)
        self.frame_contentFiles = QtWidgets.QFrame(self.frame_tabsSub)
        self.frame_contentFiles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contentFiles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contentFiles.setObjectName("frame_contentFiles")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_contentFiles)
        self.horizontalLayout_18.setContentsMargins(18, 0, 18, 9)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_listFiles = QtWidgets.QFrame(self.frame_contentFiles)
        self.frame_listFiles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_listFiles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_listFiles.setObjectName("frame_listFiles")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_listFiles)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(9)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_titleFiles = QtWidgets.QFrame(self.frame_listFiles)
        self.frame_titleFiles.setMinimumSize(QtCore.QSize(0, 33))
        self.frame_titleFiles.setMaximumSize(QtCore.QSize(16777215, 33))
        self.frame_titleFiles.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_titleFiles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_titleFiles.setObjectName("frame_titleFiles")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_titleFiles)
        self.horizontalLayout_17.setContentsMargins(0, -1, 0, 3)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.button_previous = QtWidgets.QPushButton(self.frame_titleFiles)
        self.button_previous.setMinimumSize(QtCore.QSize(50, 20))
        self.button_previous.setMaximumSize(QtCore.QSize(50, 20))
        self.button_previous.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        self.button_previous.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/graphics/icons/arrowLeft.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_previous.setIcon(icon)
        self.button_previous.setObjectName("button_previous")
        self.horizontalLayout_17.addWidget(self.button_previous)
        spacerItem1 = QtWidgets.QSpacerItem(10, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem1)
        self.label_files = QtWidgets.QLabel(self.frame_titleFiles)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_files.setFont(font)
        self.label_files.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_files.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_files.setObjectName("label_files")
        self.horizontalLayout_17.addWidget(self.label_files)
        spacerItem2 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.verticalLayout_12.addWidget(self.frame_titleFiles)
        self.list_files = QtWidgets.QListWidget(self.frame_listFiles)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.list_files.setFont(font)
        self.list_files.setStyleSheet("QListWidget\n"
"{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(180, 180, 180);\n"
"    border-radius:5px;\n"
"}\n"
"QListWidget:item:hover:!pressed\n"
"{\n"
"    background :  rgb(70, 70, 70);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(50, 50, 50);\n"
"    width: 8px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(130, 130, 130);\n"
"    min-height: 30px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 0px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 0px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.list_files.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.list_files.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.list_files.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.list_files.setViewMode(QtWidgets.QListView.ListMode)
        self.list_files.setObjectName("list_files")
        self.verticalLayout_12.addWidget(self.list_files)
        self.horizontalLayout_18.addWidget(self.frame_listFiles)
        self.frame_rightSideFiles = QtWidgets.QFrame(self.frame_contentFiles)
        self.frame_rightSideFiles.setMaximumSize(QtCore.QSize(259, 16777215))
        self.frame_rightSideFiles.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_rightSideFiles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rightSideFiles.setObjectName("frame_rightSideFiles")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_rightSideFiles)
        self.verticalLayout_11.setContentsMargins(3, 2, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem4)
        self.label_thumbnailFiles = QtWidgets.QLabel(self.frame_rightSideFiles)
        self.label_thumbnailFiles.setMinimumSize(QtCore.QSize(256, 144))
        self.label_thumbnailFiles.setMaximumSize(QtCore.QSize(256, 144))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label_thumbnailFiles.setFont(font)
        self.label_thumbnailFiles.setStyleSheet("QLabel\n"
"{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;    \n"
"    border-width: 1px;\n"
"    border-radius: 0px;\n"
"    border-color: rgb(50, 50, 50);\n"
"}\n"
"")
        self.label_thumbnailFiles.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thumbnailFiles.setObjectName("label_thumbnailFiles")
        self.verticalLayout_11.addWidget(self.label_thumbnailFiles)
        self.label_lineFiles = QtWidgets.QLabel(self.frame_rightSideFiles)
        self.label_lineFiles.setMaximumSize(QtCore.QSize(16777215, 1))
        self.label_lineFiles.setStyleSheet("border-color: rgb(180, 180, 180);\n"
"border-style:solid;\n"
"border-radius: 5px;\n"
"border-width: 1px;")
        self.label_lineFiles.setText("")
        self.label_lineFiles.setObjectName("label_lineFiles")
        self.verticalLayout_11.addWidget(self.label_lineFiles)
        self.label_commentFiles = QtWidgets.QLabel(self.frame_rightSideFiles)
        self.label_commentFiles.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_commentFiles.setFont(font)
        self.label_commentFiles.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_commentFiles.setStyleSheet("    background-color: rgb(50, 50, 50);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"    border-color: rgb(50, 50, 50);")
        self.label_commentFiles.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_commentFiles.setWordWrap(True)
        self.label_commentFiles.setObjectName("label_commentFiles")
        self.verticalLayout_11.addWidget(self.label_commentFiles)
        self.button_openFiles = QtWidgets.QPushButton(self.frame_rightSideFiles)
        self.button_openFiles.setMinimumSize(QtCore.QSize(0, 25))
        self.button_openFiles.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.button_openFiles.setFont(font)
        self.button_openFiles.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/graphics/icons/arrowUpRight.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_openFiles.setIcon(icon1)
        self.button_openFiles.setObjectName("button_openFiles")
        self.verticalLayout_11.addWidget(self.button_openFiles)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.layout_directoryFiles = QtWidgets.QHBoxLayout()
        self.layout_directoryFiles.setObjectName("layout_directoryFiles")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_directoryFiles.addItem(spacerItem6)
        self.button_directoryFiles = QtWidgets.QPushButton(self.frame_rightSideFiles)
        self.button_directoryFiles.setMinimumSize(QtCore.QSize(131, 25))
        self.button_directoryFiles.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.button_directoryFiles.setFont(font)
        self.button_directoryFiles.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/graphics/icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_directoryFiles.setIcon(icon2)
        self.button_directoryFiles.setObjectName("button_directoryFiles")
        self.layout_directoryFiles.addWidget(self.button_directoryFiles)
        self.verticalLayout_11.addLayout(self.layout_directoryFiles)
        self.horizontalLayout_18.addWidget(self.frame_rightSideFiles)
        self.verticalLayout_5.addWidget(self.frame_contentFiles)
        self.frame_informations = QtWidgets.QFrame(self.frame_tabsSub)
        self.frame_informations.setStyleSheet("")
        self.frame_informations.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_informations.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_informations.setLineWidth(0)
        self.frame_informations.setObjectName("frame_informations")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_informations)
        self.verticalLayout_4.setContentsMargins(8, 10, 9, 18)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_informations = QtWidgets.QLabel(self.frame_informations)
        self.label_informations.setMinimumSize(QtCore.QSize(0, 50))
        self.label_informations.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label_informations.setFont(font)
        self.label_informations.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_informations.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(50, 50, 50);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 255, 255);\n"
"    selection-background-color: lightgray;\n"
"}")
        self.label_informations.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_informations.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_informations.setWordWrap(True)
        self.label_informations.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_informations.setObjectName("label_informations")
        self.verticalLayout_4.addWidget(self.label_informations)
        self.verticalLayout_5.addWidget(self.frame_informations)
        self.horizontalLayout_8.addWidget(self.frame_tabsSub)
        self.verticalLayout_6.addWidget(self.frame_tabs)
        self.verticalLayout_3.addWidget(self.frame_contentSub)
        self.verticalLayout_2.addWidget(self.frame_content)
        self.frame_credit = QtWidgets.QFrame(self.frame_dropShadow)
        self.frame_credit.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_credit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_credit.setStyleSheet("QFrame\n"
"{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(27, 27, 27);\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"}\n"
"")
        self.frame_credit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_credit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_credit.setObjectName("frame_credit")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_credit)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_labelCredit = QtWidgets.QFrame(self.frame_credit)
        self.frame_labelCredit.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_labelCredit.setStyleSheet("")
        self.frame_labelCredit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_labelCredit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_labelCredit.setObjectName("frame_labelCredit")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_labelCredit)
        self.horizontalLayout_4.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_credits = QtWidgets.QLabel(self.frame_labelCredit)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgba(255, 255, 255, 128);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_4.addWidget(self.label_credits)
        self.label_version = QtWidgets.QLabel(self.frame_labelCredit)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgba(255, 255, 255, 128);")
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_4.addWidget(self.label_version)
        self.horizontalLayout_2.addWidget(self.frame_labelCredit)
        self.verticalLayout_2.addWidget(self.frame_credit)
        self.verticalLayout.addWidget(self.frame_dropShadow)
        cioxo_houdini_openWorkspace.setCentralWidget(self.central_widget)
        self.actionAbout = QtWidgets.QAction(cioxo_houdini_openWorkspace)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(cioxo_houdini_openWorkspace)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(cioxo_houdini_openWorkspace)
        QtCore.QMetaObject.connectSlotsByName(cioxo_houdini_openWorkspace)

    def retranslateUi(self, cioxo_houdini_openWorkspace):
        _translate = QtCore.QCoreApplication.translate
        cioxo_houdini_openWorkspace.setWindowTitle(_translate("cioxo_houdini_openWorkspace", "Cioxo - Project Manager"))
        self.label_welcomeFiles.setText(_translate("cioxo_houdini_openWorkspace", "Project"))
        self.label_files.setText(_translate("cioxo_houdini_openWorkspace", "Files"))
        self.list_files.setSortingEnabled(False)
        self.label_thumbnailFiles.setText(_translate("cioxo_houdini_openWorkspace", "Thumbnail"))
        self.label_commentFiles.setText(_translate("cioxo_houdini_openWorkspace", "Comment"))
        self.button_openFiles.setText(_translate("cioxo_houdini_openWorkspace", "Open"))
        self.button_directoryFiles.setText(_translate("cioxo_houdini_openWorkspace", "Directory"))
        self.label_informations.setText(_translate("cioxo_houdini_openWorkspace", ">>> Terminal"))
        self.label_credits.setText(_translate("cioxo_houdini_openWorkspace", "© 2020-2021 Valentin Beaumont"))
        self.label_version.setText(_translate("cioxo_houdini_openWorkspace", "v1.0.0"))
        self.actionAbout.setText(_translate("cioxo_houdini_openWorkspace", "v1.0.0 - © 2020-2021 Valentin Beaumont"))
        self.actionExit.setText(_translate("cioxo_houdini_openWorkspace", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cioxo_houdini_openWorkspace = QtWidgets.QMainWindow()
    ui = Ui_cioxo_houdini_openWorkspace()
    ui.setupUi(cioxo_houdini_openWorkspace)
    cioxo_houdini_openWorkspace.show()
    sys.exit(app.exec_())
